// SPDX-License-Identifier: BSD-2-Clause-Patent
//! UEFI Protocol definitions

pub mod simple_text_input;
pub mod simple_text_output;
pub mod graphics_output;
pub mod block_io;
pub mod simple_file_system;
pub mod device_path;
pub mod loaded_image;
pub mod pci_io;
pub mod usb_io;
pub mod simple_network;
pub mod firmware_management;
pub mod driver_binding;
pub mod security;
pub mod http;
pub mod tcp_udp;
pub mod hii;
pub mod shell;
pub mod ip;
pub mod pxe;
pub mod storage;
pub mod misc;
pub mod mp_services;

pub use simple_text_input::*;
pub use simple_text_output::*;
pub use graphics_output::*;
pub use block_io::*;
pub use simple_file_system::*;
pub use device_path::*;
pub use loaded_image::*;
pub use pci_io::*;
pub use usb_io::*;
pub use simple_network::*;
pub use firmware_management::*;
pub use driver_binding::*;
pub use security::*;
pub use http::*;
pub use tcp_udp::*;
pub use hii::*;
pub use shell::*;
pub use ip::*;
pub use pxe::*;
pub use storage::*;
pub use misc::*;
pub use mp_services::*;
