name: Test Suite

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Note: This is a no_std library for UEFI environments
  # Traditional unit tests with std are not applicable
  build-verification:
    name: Build Verification (no_std)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2025-01-09
        profile: minimal
        override: true
        components: rust-src

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Add UEFI target
      run: rustup target add x86_64-unknown-uefi --toolchain nightly-2025-01-09

    - name: Build library for UEFI
      run: cargo build --lib --target x86_64-unknown-uefi

    - name: Build library for UEFI (release)
      run: cargo build --lib --target x86_64-unknown-uefi --release

    - name: Report status
      run: echo "✅ Library builds successfully in no_std UEFI environment"

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2025-01-09
        profile: minimal
        override: true
        components: clippy, rust-src

    - name: Run clippy
      run: cargo clippy --lib --target x86_64-unknown-uefi -- -D warnings

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2025-01-09
        profile: minimal
        override: true
        components: rustfmt

    - name: Check formatting
      run: cargo fmt --all -- --check

  docs:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2025-01-09
        profile: minimal
        override: true
        components: rust-src

    - name: Build documentation
      run: cargo doc --lib --no-deps --all-features --target x86_64-unknown-uefi

    - name: Check for broken links
      run: |
        cargo install cargo-deadlinks
        cargo deadlinks --check-http
      continue-on-error: true
